# Site settings
title: 中极殿
email: messiahxu@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: messiahxu 
github_username: messiahxu 

# Build settings
markdown: kramdown
